### ISSUE TITLE
SQLException

### ISSUE THREAD

**Issue by nsommer** [llgb/chatVS#1]
Man übersieht die Exception fast, weil sie ganz am Anfang geworfen wird und dann das Log sehr schnell voll wird.

```
java.sql.SQLException: Column count doesn't match value count at row 1
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
    at verteilteSysteme.MySQLAccess.addUserToDB(MySQLAccess.java:214)
    at verteilteSysteme.ChatWindow.addMemberToList(ChatWindow.java:108)
    at verteilteSysteme.ChatWindow.<init>(ChatWindow.java:52)
    at verteilteSysteme.Bootstrap.main(Bootstrap.java:7)
```

**Comment by llgb** [comment]
@nsommer Die Exception kommt bei mir nicht. Kannst Du mal schauen, ob der User _chat-app_ bei dir in den Berechtigungen gesetzt wurde?

Bei mir wollte das mit dem GRANT nicht funktionieren, so dass ich ihn händisch hinzufügen musste.

**Comment by nsommer** [comment]
Die Tabelle in deiner Datenbank hat noch eine dritte Spalte `passwordhash`, die auch im Javacode gesetzt wurde. Ich hatte die Spalte aus dem SQL Skript rausgenommen, da sie keinen Sinn hat, da wir ja nicht authentifizieren.

Damit der Javacode jetzt noch bei dir geht, musst du die Spalte in deiner Datenbanktabelle löschen @llgb
